spring.application.name=crazy_bakery
spring.ai.openai.api-key=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
spring.ai.openai.image.options.model=dall-e-3
spring.ai.openai.image.options.size=1024x1024
spring.ai.openai.image.options.style=vivid
spring.ai.openai.image.options.quality=standard
spring.ai.openai.image.options.response-format=url